Imageupload/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
#This file includes all the app urls you create under this project eg:imageupload in this case
urlpatterns = [
                  url(r'^admin/', admin.site.urls),
                  url(r'', include('imageupload.urls'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

imageupload/urls.py
import views
from django.conf.urls import url

#All the urls under the 'imageupload' app reside here. They can be referred using the app_name cariable:<name of the url> for simplicity
app_name = 'appsec'
urlpatterns = [
    #Index url
    url(r'^$', views.IndexView.as_view(), name='index'),
    #image related urls
    url(r'^upload_image/$', views.GetImage.as_view(), name='get_image'),
    url(r'^update_image/(?P<image_id>.*)/$', views.ImageUpdate.as_view(), name='get_image_update'),
    url(r'^list_images/$', views.ListImage.as_view(), name='list'),
    url(r'^delete_image/$', views.Delete.as_view(), name='delete'),
    # Login urls
    url(r'^login/$', views.LoginView.as_view(), name='hl_login'),
    url(r'^logout/$', views.logout_user, name='hl_logout'),
    url(r'^register/$', views.Register.as_view(), name='register'),
]

imageupload/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User

from django.db import models
import os

#Gets the path for MEDIA_ROOT to the base MEDIA folder, so that the media gets uploaded to the right directory
def get_image_path(instance, filename):
    return os.path.join('appsec_media', str(instance.id), filename)

#APPUser inherited from the django USER for customized options and adding extra fields.
class APPUser(models.Model):
    user = models.OneToOneField(User, related_name='User')

    def __str__(self):
        return str(self.user.username) + ": " + str(self.user.email)

#Image model to upload Image to DB with fields specified as follows
#It has a foreing key user. So we can store user as a uploader in every image object
#Basically one user can upload multiple images
#All the images are uploaded to the Appsec_images folder under MEDIA folder
#Caption is editable and the IMages are filtered with their published dates
class Image(models.Model):
    user = models.ForeignKey(User)
    uploadimage = models.ImageField(upload_to='Appsec_images/%Y/%m/%d')
    caption = models.CharField(max_length=200, blank=True, null=True)
    pub_date = models.DateTimeField(auto_now_add=True)

imageupload/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from .models import Image, APPUser

# Form required for updating editing images
class ImageUploadForm(forms.ModelForm):
    uploadimage = forms.ImageField()

    def clean_uploadimage(self):
        image = self.cleaned_data.get('uploadimage')
        if image:
            if image._size > 5 * 1024 * 1024:
                raise ValidationError("Image file too large ( > 5mb )")
            return image
        else:
            raise ValidationError("Couldn't read uploaded image")
    class Meta:
        model = Image #django models a form corresponding to the Image object
        fields = ('uploadimage', 'caption')#list of fields required to be filled up or edited as a part of form

# Form required for registering
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    def clean_password(self):
        password = self.cleaned_data.get('password')
        if password:
            if len(password) < 8:
                raise ValidationError("password length too small (min 9 chars)")
            return password
        else:
            raise ValidationError("Couldn't get the password")
    class Meta:
        model = User
        fields = ('username', 'email', 'password',)

# Form required for Login
class UserProfileForm(forms.ModelForm):
    class Meta:
        model = APPUser
        fields = ('user',)


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())

imageupload/views.py
from django.contrib import messages
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404
from django.views.generic import CreateView
from django.views.generic import FormView
from braces.views import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.conf import settings
from .models import Image
from .forms import ImageUploadForm, UserForm, LoginForm
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse, reverse_lazy
from django.contrib.auth import login, authenticate, logout
from django.views.generic import View, TemplateView
from django.views.generic.edit import UpdateView

#This acts as the home page view for the app.
class IndexView(View):
    def get(self, request, *args, **kwargs):
        #Checks if the user is authenticated and redirects accordingly
        if request.user.is_authenticated():
            return HttpResponseRedirect(reverse('appsec:list'))
        else:
            return HttpResponseRedirect(reverse('appsec:hl_login'))

#This view is used to upload the images. Django CBV along with Django braces are used for checking authenticity and simplicity
class GetImage(LoginRequiredMixin, FormView):
    form_class = ImageUploadForm
    template_name = 'imageupload.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            formdata = form.cleaned_data # Here we collect all the form data and store it to the Image Object
            image = Image()
            image.caption = formdata['caption']
            obj = self.request.FILES['uploadimage']
            image.uploadimage = obj
            owner = User.objects.get(id=request.user.id)
            image.user = owner
            image.save()
            return HttpResponseRedirect(reverse('appsec:list')) #After saving the image object we riderect back to the list view
        return render(request, self.template_name, {'form': form})

#This view is used to update the images caption. Django CBV along with Django braces are used for checking authenticity and simplicity

class ImageUpdate(LoginRequiredMixin, UpdateView):
    model = Image
    fields = ['caption']
    template_name = 'imageupload_update_form.html'

    def get_object(self):
        object = get_object_or_404(Image, pk=self.kwargs['image_id'])
        return object

    def get_success_url(self):
        return reverse('appsec:list')

#This view is used to list the images. Django CBV along with Django braces are used for checking authenticity and simplicity
class ListImage(LoginRequiredMixin, TemplateView):
    template_name = "imageslist.html"
    title = "List of Images"

    def get_context_data(self, **kwargs):
        context = super(ListImage, self).get_context_data(**kwargs)
        imgs = Image.objects.all().order_by('-pub_date') #We filter the images to view the most recent images first
        if imgs.count() > 0:
            paginator = Paginator(imgs, settings.PAGINATION_LIMIT) #Access the PAGE limit set in settings file i.e 10/page
            page = self.request.GET.get('imagepage')
            try:
                final_images = paginator.page(page) #
            except PageNotAnInteger:
                final_images = paginator.page(1)
            except EmptyPage:#return rest of the remaining images
                final_images = paginator.page(paginator.num_pages)
            context['images'] = final_images
        return context

#This view is used to delete the images. Django CBV along with Django braces are used for checking authenticity and simplicity
class Delete(LoginRequiredMixin, View):
    def post(self, request, format=None):
        print "In delete", request.POST['image_id']
        image_id = int(request.POST['image_id'])
        user_id = int(request.user.id)
        if Image.objects.filter(user_id=user_id, pk=image_id).count() > 0:
            i = Image.objects.filter(user_id=user_id, pk=image_id)
            i.delete()
        return HttpResponseRedirect(reverse('appsec:list'))

#View to logout from the app with a decorator to check that logout takes place only when user is logged in
@login_required
def logout_user(request):
    logout(request)
    messages.success(request, 'You have successfully logged out.')
    return HttpResponseRedirect(reverse('appsec:hl_login')) #redirects to the login page

#View to register new users
class Register(CreateView):
    template_name = 'register.html'
    form_class = UserForm
    success_url = reverse_lazy('appsec:list')  #redirects to the list view page
    model = User

    def get_success_url(self):
        form = self.get_form(self.form_class)
        if form.is_valid():
            if self.object:# Here we collect all the form data and store it to the User Object
                self.object.set_password(form.cleaned_data['password'])
                self.object.save()
                username = self.object.username
                password = form.cleaned_data['password']
                user = authenticate(username=username, password=password)
                if user:
                    login(self.request, user)
        return super(Register, self).get_success_url()

#View to login existing users
class LoginView(CreateView):
    form_class = LoginForm
    template_name = 'auth.html'

    def get(self, request, *args, **kwargs):
        return render(self.request, self.template_name, {'form': self.form_class})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():
            formdata = form.cleaned_data # Here we collect all the form data and store it to the Image Object
            username = formdata['username']
            password = formdata['password']
            user = authenticate(username=username, password=password)
            if user:
                login(self.request, user)
                return HttpResponseRedirect(reverse('appsec:list')) #redirects to the list view page after authenticating
        return render(request, self.template_name, {'form': self.form_class})

imageupload/templates/auth.html
{% extends 'base.html' %}
{% block content %}
<ul>
    <li><img src="/appsec_media/nyu.jpg" width="45" height="45"/></li>
    <li><a href=""><b>SIGN-IN</b></a></li>
    <li><a href="{% url 'appsec:register' %}"><b>REGISTER</b></a></li>
</ul>
<center>
    <form method="post" action="{% url 'appsec:hl_login' %}" enctype="multipart/form-data">
        <label><h3>Welcome! Please log in below...</h3></label>
        {% csrf_token %}
        {{ form.username.errors }}<br>
        <label>Username: </label><br>{{ form.username }}
        {{ form.password.errors }}<br>
        <label>Password: </label><br> {{ form.password }}<br><br>
        <input type="submit" name="submit" value="Log in"/>
    </form>
</center>
{% endblock %}

imageupload/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Application security</title>
    <style>
        table, th, td {
            border: 1px solid gray;
            border-collapse: collapse;
        }
        th, td {
            text-align: center;
            padding: 5px;

        }
        ul {
            list-style-type: none;
            overflow: hidden;
            background-color: #57068c;
        }
        li {
            float: left;
        }
        li a:hover {
            background-color: #111;
        }
        li a {
            display: block;
            color: white;
            padding: 15px 20px;
        }

    </style>
</head>
<body background="/appsec_media/bg.jpg" style="">
{% if user.is_authenticated %}
<ul>
    <li><img src="/appsec_media/nyu.jpg" width="45" height="45"/></li>
    <li><a href="{% url 'appsec:hl_logout' %}">LOGOUT(-)</a></li>
    <li><a href="{% url 'appsec:get_image' %}"><-UPLOAD IMAGE</a></li>
    <li><a href="{% url 'appsec:list' %}"><-IMAGE LIST</a></li>
</ul>
{%endif%}
{% block content %}{% endblock %}
</body>
</html>

imageupload/templates/imageslist.html
{% extends 'base.html' %}
{% block content %}
<ul>
    {% if images.has_previous %}
    <li><a href="?imagepage={{ images.previous_page_number }}"><-BACK</a></li>
    {% endif %}
    <li><a>Imagepage {{ images.number }} <-> {{ images.paginator.num_pages }}.</a></li>
    {% if images.has_next %}
    <li><a href="?imagepage={{ images.next_page_number }}">NEXT-></a></li>
    {% endif %}
</ul>
<center>
    <h3>{{ view.title }}</h3>
    <table style="width:70%">
        <tr>
            <th>Image Id</th>
            <th>Image Caption</th>
            <th>Username(Uploader)</th>
            <th>Image</th>
            <th>Image Name</th>
            <th>Published date</th>
            <th>Action</th>
        </tr>
        {% for image in images %}
        <tr>
            <th>{{image.id}}</th>
            <th>{{image.caption}}</th>
            <th>{{image.user.username}}</th>
            <th><img src="{{ image.uploadimage.url}}" alt="{{image.uploadimage.name}}" height="200" width="400"
                     align="middle"/></th>
            <th>{{image.uploadimage.name}}</th>
            <th>{{image.pub_date}}</th>
            <th>
                <!--<form action="/update_image/?pk={{image.id}}" method="GET">&ndash;&gt;-->
                <!--&lt;!&ndash;{% csrf_token %}&ndash;&gt;-->
                <!--&lt;!&ndash;<button type="submit" value="{{image.id}}" name="pk">Edit</button>&ndash;&gt;-->
                <!--&lt;!&ndash;</form>-->
                <a href="{% url 'appsec:get_image_update' image_id=image.id %}">EDIT</a>
            </th>

            <th>
                <form action="/delete_image/" method="POST">
                    {% csrf_token %}
                    <button type="submit" value="{{image.id}}" name="image_id">Delete</button>
                </form>
            </th>
        </tr>
        {% endfor %}

    </table>
</center>
{% endblock %}

imageupload/templates/imageupload.html
{% extends 'base.html' %}
{% block content %}
<center>
    <h3>Manage Image Upload</h3>
    <form enctype="multipart/form-data" method="post" action="">
        {% csrf_token %}
        {{ form.as_p}}
        <input type="submit" value="Upload" onclick=""/>
    </form>
</center>
{% endblock %}

imageupload/templates/imageupload_update_form.html
{% extends 'base.html' %}
{% block content %}
<center>
    <h3>Manage Image Upload</h3>
    <form enctype="multipart/form-data" method="post" action="">
        {% csrf_token %}
        {{ form.as_p}}
        <input type="submit" value="Update"/>
    </form>
</center>
{% endblock %}

imageupload/templates/register.html
{% extends 'base.html' %}
{% block content %}
<ul>
    <li><img src="/appsec_media/nyu.jpg" width="45" height="45"/></li>
    <li><a href="{% url 'appsec:hl_login' %}"><b>SIGN-IN</b></a></li>
    <li><a href=""><b>REGISTER</b></a></li>
</ul>
<center>
    {% if registered %}
    <strong>Thank you for registering!</strong>
    <a href="{% url 'appsec:list' %}">Return to the homepage.</a>
    {% else %}
    <form id="hlform_login" method="post" action="{% url 'appsec:register' %}" enctype="multipart/form-data">
        <label><h3>Welcome! Please register below...</h3></label>
        {% csrf_token %}
        {{ form.username.errors }}<br>
        <label>Username:</label><br>{{ form.username }}
        {{ form.password.errors }}<br>
        <label>Password:</label><br>{{ form.password }}
        {{ form.email.errors }}<br>
        <label>Email:</label><br>{{ form.email }}<br><br>
        <input type="submit" name="submit" value="Register"/>
    </form>
    {% endif %}

</center>
{% endblock %}